sudo: required

language: generic

services:
  - docker

env:
  - TAG=zbarcam-linux DOCKERFILE=dockerfiles/Dockerfile-linux COMMAND='make test'
  - TAG=zbarcam-android DOCKERFILE=dockerfiles/Dockerfile-android COMMAND='buildozer android debug'

install:
  - docker build --tag=$TAG --file=$DOCKERFILE .

script:
  - travis_wait docker run $TAG $COMMAND
